"use strict";

exports.GENERAL_ERROR = 'GENERAL_ERROR';

exports.ENABLE_EDITING = 'ENABLE_EDITING';
exports.DISABLE_EDITING = 'DISABLE_EDITING';

exports.RESET_LAYOUT_GROUPS = 'RESET_LAYOUT_GROUPS';
exports.ADD_LAYOUT_GROUP = 'ADD_LAYOUT_GROUP';
exports.REMOVE_LAYOUT_GROUP = 'REMOVE_LAYOUT_GROUP';

exports.ADD_LAYOUT = 'ADD_LAYOUT';
exports.REMOVE_LAYOUT = 'REMOVE_LAYOUT';
exports.UPDATE_LAYOUT = 'UPDATE_LAYOUT';

Object.freeze(exports);
